openapi: 3.0.3
info:
  title: Api Proveedores
  version: 1.0.0
tags:
  - name: Proveedores
    description: Endpoints relacionados a proveedores 
  - name: Fabricantes
    description:  Endpoints relacionados a fabricantes
  - name: Login
    description: Endpoints relacionados a la autenticacion JWT
paths:
  /suppliers:
    get:
      tags:
        - Proveedores
      summary: Listar todos los proveedores que hay en la nube
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Suppliers'          
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header || token has expired'
  /suppliers/by_data:
    post:
      tags:
        - Proveedores
      summary: Listar todos los proveedores disponibles
      description: Se listan los proveedores que pueden satisfacer los requerimientos del cliente, tales sean la fecha, el material, la cantidad y opcionalmente el precio maximo tolerado.
      requestBody:
        description: Parametros para la busqueda de proveedores determinados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestProveedoresByData'
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseProveedoresByData' 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: 'Materials required'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header || token has expired'
  /suppliers/reserve:
    post:
      tags:
        - Proveedores
      summary: Reservar los proveedores elegidos
      description: Se reserva la cantidad de materiales a los proveedores que el cliente eligio para la fecha solicitada
      requestBody:
        description: Parametros para la busqueda de proveedores determinados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestProveedoresReserve'
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProveedoresReservados' 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: 'Suppliers required'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header|| token has expired'
                    
  /makers:
    get:
      tags:
        - Fabricantes
      summary: Listar todos los fabricantes que hay en la nube
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Makers'          
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header || token has expired'
  /makers/by_data:
    post:
      tags:
        - Fabricantes
      summary: Listar todos los fabricantes disponibles
      description: Se listan los fabricantes que pueden satisfacer los requerimientos del cliente, tales sean la fecha, el material, la cantidad y opcionalmente el precio maximo tolerado.
      requestBody:
        description: Parametros para la busqueda de fabricantes determinados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestFabricantesByData'
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFabricantesByData' 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: 'Materials required'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header || token has expired'
  /makers/reserve:
    post:
      tags:
        - Fabricantes
      summary: Reservar los fabricantes elegidos
      description: Se reserva la cantidad de materiales a los fabricantes que el cliente eligio para la fecha solicitada
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FabricantesReservados' 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: 'Makers required'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Missing Authorization Header'
  
  /login:
    post:
      tags:
        - Login
      summary: Autenticarse con el sistema
      description: Se ingresa user y password para logearse y retornar un token jwt para poder realizar las consultas
      requestBody:
        description: Parametros para la busqueda de proveedores determinados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLogin'
      responses:
        '200':
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutenticacionExitosa' 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: 'Provide username and password in JSON format in the request body'
        '401':
          description: No autenticado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 'Bad username or password'
components:
  schemas:
    AutenticacionExitosa:
        type: object
        properties:
            access_token:
                  type: string
                  example: "asdggstg46yadgagaetyyt6wytjehgfoiueqhgoiquyg8q7wgtyq78g8qghq8yug7hq8g"
    ResponseProveedoresByData:
        type: object
        properties:
            metadata:
                  type: object
                  properties:
                    materiales_sin_proveedor:
                      type: array
                      items:
                        type: object
                        properties:
                          amount:
                            type: integer
                            example: 15
                          date_required:
                            type: string
                            example: "17/12/2022"
                          name:
                            type: string
                            example: 'Madera'
            suppliers:
              type: array
              items:
                $ref: '#/components/schemas/Supplier'  
    RequestLogin:
        type: object
        properties:
          username:
            type: string
            example: "walter.bates"
          password:
            type: string
            example: admin123
    RequestProveedoresByData:
        type: object
        properties:
          materiales:
            type: array
            items:
              type: object
              properties:
                amount:
                  type: integer
                  example: 15
                date_required:
                  type: string
                  example: "17/12/2022"
                name:
                  type: string
                  example: 'Madera'
          filtro_precio:
            type: integer
            example: 1000
          dias_extras:
            type: integer
            example: 5
    ProveedoresReservados:
      type: object
      properties:
        response:
          type: array
          items:
            type: object
            properties:
              material_id:
                type: integer
                example: 2
              message:
                type: string
                description: dependiendo si el proveedor seguia con stock suficiente se informa reserva exitosa o proveedor sin stock
                example: "Proveedor sin stock || reserva exitosa"
              supplier_id:
                type: integer
                example: 3
    RequestFabricantesByData:
        type: object
        properties:
          materiales:
            type: array
            items:
              type: object
              properties:
                amount:
                  type: integer
                  example: 15
                date_required:
                  type: string
                  example: "17/12/2022"
                name:
                  type: string
                  example: 'Madera'
          filtro_precio:
            type: integer
            example: 1000
          dias_extras:
            type: integer
            example: 5
    FabricantesReservados:
      type: object
      properties:
        response:
          type: array
          items:
            type: object
            properties:
              material_id:
                type: integer
                example: 2
              message:
                type: string
                description: dependiendo si el proveedor seguia con stock suficiente se informa reserva exitosa o proveedor sin stock
                example: "Fabricante sin stock || reserva exitosa"
              maker_id:
                type: integer
                example: 3
    ResponseFabricantesByData:
        type: object
        properties:
            metadata:
                  type: object
                  properties:
                    materiales_sin_proveedor:
                      type: array
                      items:
                        type: object
                        properties:
                          amount:
                            type: integer
                            example: 15
                          date_required:
                            type: string
                            example: "17/12/2022"
                          name:
                            type: string
                            example: 'Madera'
            makers:
              type: array
              items:
                $ref: '#/components/schemas/Maker'  
    RequestProveedoresReserve:
        type: object
        properties:
          suppliers:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                materials:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 3
                      amount:
                        type: integer
                        example: 15
    Suppliers:
      type: object
      properties:
        suppliers:
          type: array
          items:
            $ref: '#/components/schemas/Supplier'
    Supplier:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        materials:
          type: array
          items:
            type: object
            properties:
              date_deliver:
                type: string
                example: "17/12/2022"
              id:
                type: integer
                example: 1
              name:
                type: string
                example: vidrio
              price_per_kg:
                type: number
                example: 250.0
        name:
          type: string
          example: "pepe"
    Makers:
      type: object
      properties:
        makers:
          type: array
          items:
            $ref: '#/components/schemas/Maker'
    Maker:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        materials:
          type: array
          items:
            type: object
            properties:
              date_deliver:
                type: string
                example: "17/12/2022"
              id:
                type: integer
                example: 1
              name:
                type: string
                example: vidrio
              price_per_kg:
                type: number
                example: 250.0
        name:
          type: string
          example: "pepe"